/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.PerturbedStarCertificates
-/

import Mathlib.Algebra.Group.Nat.Range
import Mathlib.Data.Fin.Embedding
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Image
import Mathlib.Tactic
import UniformMissingTraceFamily.Main.PatternCriterion.Interfaces
