/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.PerturbedPatternCancellation
-/

import UniformMissingTraceFamily.Main.PerturbedPatternCancellation.Theorems.perturbedPattern_properWeights_add_full_eq_fullWeights
