/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.CountingAndMain
-/

import UniformMissingTraceFamily.Main.CountingAndMain.Theorems.exists_uniformMissingTraceFamily_strictlyLargerThanStar
import UniformMissingTraceFamily.Main.CountingAndMain.Theorems.perturbedStarFamily_card
