/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.CountingAndMain
-/

import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Defs
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Filter
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Data.Nat.Choose.Vandermonde
import UniformMissingTraceFamily.Main.AnchoredPowersetEnumeration.Interfaces
import UniformMissingTraceFamily.Main.PatternCriterion.Interfaces
import UniformMissingTraceFamily.Main.PerturbedPatternCancellation.Interfaces
import UniformMissingTraceFamily.Main.PerturbedStarCertificates.Interfaces
