/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.PatternCriterion
-/

import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Lattice.Basic
import Mathlib.Data.Finset.Powerset
