/-
This file is generated by Lean Constellation.
Do not edit manually.
Node: Main.AnchoredPowersetEnumeration
-/

import UniformMissingTraceFamily.Main.AnchoredPowersetEnumeration.Theorems.anchoredPowerset_weightedSum_eq_chooseSum
